### ISSUE TITLE
Unable to import OMS Dashboards

### ISSUE THREAD

**Issue by tankeehock** [Azure/pci-paas-webapp-ase-sqldb-appgateway-keyvault-oms#7]
The scripts to import the OMS dashboards are outdated. For example, the use of "Type=sqlazure_CL" is no longer supported. For more references, take a look [here](https://blogs.technet.microsoft.com/msoms/2017/01/17/enable-azure-resource-metrics-logging-using-powershell/) at Jim Britt's comments on "sqlazure_CL".

**Comment by simorjay** [comment]
The OMS dashboard where deprecated.
